### PR TITLE
Docker Support

### PR DESCRIPTION
**Pull request by pdrivom**
- Dockerfile added for development propose only.
 - docker-compose added for development propose only.
 - README updated with instructions for development in Docker containers.

### CODE REVIEW

**Comment by pdrivom** [comment]
I think the Codacy code analysis for Docker file can be ignored. Since It's using multi-stage build, the dev image doesn't need this kind of pattern. For production it makes sense to add an adicional stage to be cleaner and with minimal number of packages.

**Comment by seapagan** [comment]
Thanks for this @pdrivom :+1: 

> I think the Codacy code analysis for Docker file can be ignored. Since It's using multi-stage build, the dev image doesn't need this kind of pattern. For production it makes sense to add an adicional stage to be cleaner and with minimal number of packages.

I can add the Dockerfile to Codacy's ignore list. However, it wouldn't be a bad idea to pin the installation to 1.5.0 as it suggests. Poetry is not known for breaking things on upgrade though.

I'll take a look at the PR later tonight, I have a lot of real-world stuff to do today I've been putting off :smile:

**Comment by seapagan** [comment]
@pdrivom I will look at your PR this afternoon; sorry for the delay.

Can you please add relevant Docker information to the Docs source in `docs/development/docker.md` also? I've created a blank file there for this use. You can find info on updating the docs at <https://seapagan.github.io/fastapi-template/development/documentation/>, just follow a similar style to that in  `docs/development/local.md` :+1: 

Thanks :smile:

**Comment by seapagan** [comment]
@pdrivom I've come upon a couple of issues after trying the Docker solution: 

1) `docker-compose` (v1) is deprecated (and will be removed from Docker after June this year) and should be replaced by `docker compose` (v2) - see https://docs.docker.com/compose/migrate/
2) Postgresql port **5432** interferes with a local installation of Postgresql. Can you change the mapped port to (e.g.) 5433, please? I have to disable my local PostgreSQL to run the container.
3) Can you please show me the local `.env` file you use for this? I get connection refused. Obv remove any private data :stuck_out_tongue_winking_eye:  
image

For info, I'm working on Ubuntu 22:04

**Comment by seapagan** [comment]
>     1. No problem, I will make the necessary changes in order to make compatible to docker compose v2 (the changes are mainly on the commands syntax).

Great ta. Yeah, it's mainly a syntax change for this Repo, but there are other changes or regressions, and the old version won't be installed by default very soon.

>     2. Ok, no worries, I can remove/make it configurable the port attribute, I usually keep it so it can be connected via pgAdmin or Workbench.

Cheers :smile: 
 
>     3. I use the .env.example, I specify on docs that the file should be renamed to .env. It's the fastapi and docker compose that are using the same .env file, so If changes on .env file, would make the change on the postgres container and fastapi container.
>        We can find a way to make the .env default for dev only.

Yeah, it may be a difference in my system, which OS are you developing on? I did rename the example .env and got the same error. I'll take a closer look tomorrow. 

Thanks for your help :)

**Comment by pdrivom** [comment]
Ah, I know what is wrong, you .env.example is using localhost as `DB_ADDRESS` and it should have the hostname of the db service. I will update that and make it configurable as well.

Cheers mate.

**Comment by seapagan** [comment]
> Ah, I know what is wrong, you .env.example is using localhost as `DB_ADDRESS` and it should have the hostname of the db service. I will update that and make it configurable as well.
> 
> Cheers mate.

I got it working that way ta, though I had to delete the Docker volume so it created the User properly. 

The issue we have now is that you don't migrate the database (since we use `Alembic` migrations, the database needs to be configured before the server is run) so the server crashes as it can't find the correct tables.

You can do this with the following docker command :

```console
$ docker compose run --rm --service-ports api alembic upgrade head
[+] Building 0.0s (0/0)                                                                                                                                                                                            
[+] Creating 1/0
 ✔ Container containerized-fastapi-template-db-1  Running                                                                                                                                                     0.0s 
[+] Building 0.0s (0/0)                                                                                                                                                                                            
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 1850712f171b, Initial
INFO  [alembic.runtime.migration] Running upgrade 1850712f171b -> 3ef701c22cf8, Add banned field to database
INFO  [alembic.runtime.migration] Running upgrade 3ef701c22cf8 -> 4cab6fd22890, Add verified flag
```

Can you please mention this in the docs, or add that to the compose file to run after the DB is ready?

There is a second issue, which is my oversight, in that when registering a user the API errors d/t the default `.env.example` file has dummy Mail Server info.

I don't want to put valid server info in the example file obviously, so I can either:
1) Update the documentation to make it clearer that you need to set up the mail server. I'll also mention <https://mailtrap.io> which is brilliant for testing mail functionality 
2) Test the mail server on startup and disable mail sending if that is invalid. However, I don't want it to silently fail without letting the operator know either.

I'll have a play today and probably do a mixture of both.

**Comment by pdrivom** [comment]
Hello @seapagan , ok, I will add the migration option.

**Comment by seapagan** [comment]
> Hello @seapagan , ok, I will add the migration option.

Great Ta

Sorry to push but if you could also add docs as this comment [above](https://github.com/seapagan/fastapi-template/pull/101#issuecomment-1587364660)

Cheers! :smile:

**Comment by pdrivom** [comment]
Hello @seapagan , no problem, already updated the README and docker compose, I will take care of docker.md and push everything together.

Cheers!

**Comment by seapagan** [comment]
@pdrivom

That's great, thank you for this contribution, I will merge this as it is. :smiley: 

I have a few more tweaks to add to other parts of the project then I'll release version 1.6.0.

**Pull request merged**
